### ISSUE TITLE
No instructions to make shell scripts executable

### ISSUE THREAD

**Issue by davidaylaian** [no92/vineyard#8]
When cloning vineyard, the shell scripts that the build process rely on don't have executable permissions. Can you please add commands to make them executable to your README, so that people don't get confused when they get a permission denied error? Thanks.

**Comment by no92** [comment]
Starting with b5469bcc5662865c2ef8edf3ab8cdda01cf0ac2f, all scripts should be made executable before being run.

Feel free to reopen if issues arise, but as it seems to be fixed based on testing with my secondary machine I'm closing this for now.
